FROM chillerrobot/ros-noetic-moveit-panda:first

#RUN apt-get install -y --no-install-recommends *add your installs here*
#RUN pip3 install *add your packages here*

RUN echo "source ./catkin_ws/devel/setup.bash" >> ~/.bashrc